### ISSUE TITLE
gnomeTheme.tabsAsHeaderbar broken on Firefox 113

### ISSUE THREAD

**Issue by SoiledBrush** [rafaelmardojai/firefox-gnome-theme#617]
**Describe the bug**
Exit button disappeared with Firefox version 113

**To Reproduce**
I updated to Firefox 113. Tried both master and beta versions of the theme. Tried reinstalling firefox with new profile.

**Expected behavior**
Existing exit button to click on, tried enabling minimize and maximize button in gnome-tweaks. They also won`t appear.

**Screenshots**
![Screenshot from 2023-05-10 00-36-47](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/43366389/d86930b1-8f7d-4f2c-8bd3-4ab15795f231)

**Setup information**
 - OS: Fedora 38 
 - Installation method: Flarpak
 - Firefox version: 113
 - Theme version: 112, master and beta
 - Optional features enabled: 
    gnomeTheme.normalWidthTabs true
    gnomeTheme.tabsAsHeaderbar true

**Comment by rafaelmardojai** [comment]
I'm updating the theme for `113` and is mostly fixed, but `gnomeTheme.tabsAsHeaderbar` is currently broken.

**Comment by rafaelmardojai** [comment]
Fixed on [2cc8726c553d245383aa607caa2dbf5d7416f977]

**Comment by queeup** [comment]
New version for this fix?

**Comment by elmagio** [comment]
For clarification, is the fix supposed to fix tabsAsHeaderbar? For me, with the Firefox installed from Flathub and the theme's v113 (curl method), the option is still broken and displays like this:
![Capture d’écran du 2023-05-12 12-52-16](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/14126056/cdc7cbbc-ede0-4e2d-9b37-cc739cd3a1af)

**Comment by elmagio** [comment]
> > For clarification, is the fix supposed to fix tabsAsHeaderbar? For me, with the Firefox installed from Flathub and the theme's v113 (curl method), the option is still broken and displays like this: ![Capture d’écran du 2023-05-12 12-52-16](https://user-images.githubusercontent.com/14126056/237951667-cdc7cbbc-ede0-4e2d-9b37-cc739cd3a1af.png)
> 
> I still get the same issue with the lastest commit, any update on this?

Upon further experimentation, I realized the issue came from having `gnomeTheme.bookmarksToolbarUnderTabs` enabled at the same time as `gnomeTheme.tabsAsHeaderbar`, at least for me.

Since `gnomeTheme.bookmarksToolbarUnderTabs` doesn't actually do anything while `gnomeTheme.tabsAsHeaderbar` is enabled, it isn't really an issue.

**Comment by yukina3230** [comment]
Thank you, I fixed my issue by set `gnomeTheme.bookmarksToolbarUnderTabs` to `false`
